language: php

php: ["5.3", "5.4", "5.5", "hhvm"]

matrix:
  allow_failures:
    - php: hhvm

env:
  global:
    - ARCHER_PUBLISH_VERSION=5.5
    - secure: "GtqSwiPd1SWRw4SvHsq1FIgyA6PMmBAWyJA5/4DHXS5u5CZGS+oHutO5z9qGBqP9H5924t+HG43pUd1nIP4yCRNYB8axfKQY+aasXbKX6iZBOanRsxjmsRxkdd4T2BXGCA3vxXkV0/w7UOSPaiX0Lf2Bx1d09MCWwCTPwXnTOk4="

install:
  - ./.travis.install

script:
  - ./vendor/bin/archer travis:build
